# Site settings 基础设置
title: One-Punch-Man                  #你博客的标题
SEOTitle: 一拳超人的博客 | One-Punch-Man     #显示在浏览器上搜索的时候显示的标题
header-img: img/man-1.jpg                #显示在首页的背景图片
email: liu1423248687@gmail.com  #你的邮箱
description: "Every failure is leading towards success."    #网站介绍
keyword: "Liuzebo"      #关键词
url: "http://1423248687.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/1423248687/1423248687.github.io.git" # you code repository  代码在git上的位置

# Sidebar settings  侧边栏
sidebar: true                           # whether or not using Sidebar.  是否开启侧边栏
sidebar-about-description: "对不起！我只需要一拳！" #个人语录
sidebar-avatar: /img/touxiang.png      # 个人头像



# SNS settings  #社交账号
RSS: false  
# weibo_username:     qiubaiying
zhihu_username:     liuzebo
github_username:    1423248687
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying



#系统配置 不要更改
# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10            #每一页显示十篇文章
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]      #转换时排除某些文件、文件夹
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


#系统配置 不要更改
# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



#系统配置 不要更改
# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统   不需要就注释
# # Disqus（https://disqus.com/）
# # disqus_username: qiubaiying

# # Gitalk
# gitalk:
#  enable: true    #是否开启Gitalk评论
#  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
#  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
#  repo: qiubaiying.github.io    #仓库名称
#   #owner: qiubaiying    #github用户名
#   #admin: qiubaiying
#   #distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计 不需要刻意删除或者注释

# # Analytics settings
# # Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# # Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags 标签的开启
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color:"red" #标签颜色
service-worker: true



# Friends  好友
# friends: [
#     {
#         title: "WY",
#         href: "http://zhengwuyang.com"
#     },{
#         title: "简书·BY",
#         href: "http://www.jianshu.com/u/e71990ada2fd"
#     },{
#         title: "Apple",
#         href: "https://apple.com"
#     },{
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]
